// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8U1RhiDXDyKxoMNxH86ORCuyVlWsR6-A',
    appId: '1:241194493021:android:6801e4137b962d6d7519b4',
    messagingSenderId: '241194493021',
    projectId: 'ecommerce360-21b01',
    storageBucket: 'ecommerce360-21b01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuGTNlGuz8vxWSw61mn7lKQ5CKRH0LhsY',
    appId: '1:241194493021:ios:010e5ccbd398946a7519b4',
    messagingSenderId: '241194493021',
    projectId: 'ecommerce360-21b01',
    storageBucket: 'ecommerce360-21b01.firebasestorage.app',
    androidClientId: '241194493021-c7d8qc2o7pidromna72b2uilg2bncrsj.apps.googleusercontent.com',
    iosClientId: '241194493021-vbm64nie72hkka8lv9f27t5v9i696pjm.apps.googleusercontent.com',
    iosBundleId: 'com.example.deliverymanApp',
  );
}
